package repository.annotations

/**
 * Marks a property as the primary key of an entity.
 *
 * @property autoIncrement Whether the primary key value should be automatically
 *                         generated by the database (e.g., AUTO_INCREMENT in MySQL).
 */
@Target(AnnotationTarget.CLASS, AnnotationTarget.VALUE_PARAMETER)
@Retention(AnnotationRetention.RUNTIME)
annotation class Id(
    val autoIncrement: Boolean = true,
)
